site_name: "Peasy"
site_url: http://p-org.github.io/Peasy/
site_description: "Peasy: An Intuitive Development Environment for P"
site_author: "P Team @ AWS"

repo_url: https://github.com/p-org/peasy-ide-vscode
repo_name: Peasy-ide-vscode
edit_uri: ""

theme:
  language: en
  name: material
  palette:
    scheme: default
    primary: black
    accent: deep orange
  logo: images/p-icon.png
  favicon: images/p-icon.png
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
    - toc.follow

# This should be renamed to nav for mkdocs 1.0+
nav:
  - Peasy: index.md
  - Install: installingPeasy.md
  - User Guide:
    - Compiling Code: compilingCode.md
    - Running Testcases: runningTestcases.md
    - Editing Code: editingCode.md
    - State Machine Visualizer: visualizingStateMachines.md
    - Trace Visualizer:
      - Getting Started: trace-visualizer/getting_started.md
      - Features:
        - Basics: trace-visualizer/feature_basics.md
        - Trace Filtering: trace-visualizer/feature_search_bar.md
        - Motifs: trace-visualizer/feature_motifs.md
        - Compare and Contrast: trace-visualizer/feature_compare_contrast.md
      - P JSON Output: trace-visualizer/p_json_output.md
    - Keyboard Shortcuts and Commands: shortcutsAndCommands.md
  - Peasy Demo Video: demo.md
  - Contributing to Peasy: contribute.md
  
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.critic
  - attr_list
  - footnotes
  - attr_list 
  - md_in_html
  - pymdownx.keys
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - toc:
      toc_depth: 4

plugins:
  - search:
      separator: '[\s\-\.]+'

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:ankushdesai@gmail.com
      name: Contact P Team
  analytics:
    provider: google
    property: G-0WWG87T6BN
extra_css:
  - "css/extra.css"

copyright: Copyright &copy; 2023 P Developers